#!/bin/bash
# literature-search 示例脚本
# 此脚本演示了如何使用 QwenPaw 的 browser_use 工具进行学术文献检索
# 实际使用时，这些步骤需要在 QwenPaw 代理中通过调用 browser_use 工具来执行

echo "=== Google Scholar 文献检索示例 ==="
echo ""
echo "步骤 1：启动浏览器（无头模式）"
echo "  工具调用: browser_use(action='start', headed=False)"
echo ""
echo "步骤 2：打开 Google Scholar"
echo "  工具调用: browser_use(action='open', url='https://scholar.google.com', page_id='scholar')"
echo ""
echo "步骤 3：等待页面加载完成"
echo "  工具调用: browser_use(action='wait_for', text_gone='正在加载', page_id='scholar', wait_time=5000)"
echo ""
echo "步骤 4：定位搜索框并输入关键词"
echo "  先获取页面元素引用:"
echo "    browser_use(action='snapshot', page_id='scholar')"
echo "  然后从返回的引用中找到搜索框（通常是输入框）"
echo "  工具调用: browser_use(action='type', text='您的研究关键词', ref='<搜索框引用>', page_id='scholar')"
echo ""
echo "步骤 5：提交搜索"
echo "  工具调用: browser_use(action='press_key', key='Enter', page_id='scholar')"
echo ""
echo "步骤 6：等待搜索结果加载"
echo "  工具调用: browser_use(action='wait_for', text_gone='正在加载', page_id='scholar', wait_time=5000)"
echo ""
echo "步骤 7：获取搜索结果快照"
echo "  工具调用: browser_use(action='snapshot', page_id='scholar', snapshot_filename='scholar_results_$(date +%Y%m%d_%H%M%S).txt')"
echo ""
echo "步骤 8：从结果中提取信息（示例）"
echo "  获取第一条结果标题:"
echo "    browser_use(action='get', text='<第一条结果标题引用>', page_id='scholar')"
echo "  获取第一条结果链接:"
echo "    browser_use(action='get', attr='href', ref='<第一条结果链接引用>', page_id='scholar')"
echo ""
echo "步骤 9：可选：导出为 BibTeX 格式"
echo "  需要解析快照内容，提取标题、作者、摘要、期刊、年份等信息"
echo "  然后格式化为 BibTeX 条目"
echo ""
echo "步骤 10：关闭浏览器"
echo "  工具调用: browser_use(action='stop')"
echo ""
echo "=== 完成 ==="
echo "提示：实际使用时，请将上述工具调用转换为对应的 QwenPaw 工具使用方式。"